export const FETCH_SUBMIT = 'FETCH_SUBMIT';
export const FETCH_SUBMIT_PENDING = 'FETCH_SUBMIT_PENDING';
export const FETCH_SUBMIT_FULFILLED = 'FETCH_SUBMIT_FULFILLED';
export const FETCH_SUBMIT_REJECTED = 'FETCH_SUBMIT_REJECTED';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES_PENDING = 'FETCH_CATEGORIES_PENDING';
export const FETCH_CATEGORIES_FULFILLED = 'FETCH_CATEGORIES_FULFILLED';
export const FETCH_CATEGORIES_REJECTED = 'FETCH_CATEGORIES_REJECTED';
